/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULATOR_H_RPCGEN
#define _CALCULATOR_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct input {
	int input_1;
	int input_2;
};
typedef struct input input;

#define calculator 0x30000001
#define calculator_demo 1

#if defined(__STDC__) || defined(__cplusplus)
#define sum 1
extern  int * sum_1(input *, CLIENT *);
extern  int * sum_1_svc(input *, struct svc_req *);
#define substract 2
extern  int * substract_1(input *, CLIENT *);
extern  int * substract_1_svc(input *, struct svc_req *);
#define multiply 3
extern  int * multiply_1(input *, CLIENT *);
extern  int * multiply_1_svc(input *, struct svc_req *);
#define divide 4
extern  float * divide_1(input *, CLIENT *);
extern  float * divide_1_svc(input *, struct svc_req *);
extern int calculator_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define sum 1
extern  int * sum_1();
extern  int * sum_1_svc();
#define substract 2
extern  int * substract_1();
extern  int * substract_1_svc();
#define multiply 3
extern  int * multiply_1();
extern  int * multiply_1_svc();
#define divide 4
extern  float * divide_1();
extern  float * divide_1_svc();
extern int calculator_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_input (XDR *, input*);

#else /* K&R C */
extern bool_t xdr_input ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULATOR_H_RPCGEN */
