/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <stdio.h>
#include <stdlib.h>

#include "calculator.h"

void calculator_1(char* host) {
  CLIENT* clnt;
  int* result_1;
  input sum_1_arg;
  int* result_2;
  input substract_1_arg;
  int* result_3;
  input multiply_1_arg;
  float* result_4;
  input divide_1_arg;

#ifndef DEBUG
  clnt = clnt_create(host, calculator, calculator_demo, "udp");
  if (clnt == NULL) {
    clnt_pcreateerror(host);
    exit(1);
  }
#endif /* DEBUG */

  sum_1_arg.input_1 = 5;
  sum_1_arg.input_2 = 6;
  result_1 = sum_1(&sum_1_arg, clnt);
  if (result_1 == (int*) NULL) { clnt_perror(clnt, "call failed"); }
  printf("%i + %i = %i\n", sum_1_arg.input_1, sum_1_arg.input_2, *result_1);

  substract_1_arg.input_1 = 11;
  substract_1_arg.input_2 = 7;
  result_2 = substract_1(&substract_1_arg, clnt);
  if (result_2 == (int*) NULL) { clnt_perror(clnt, "call failed"); }
  printf("%i - %i = %i\n", substract_1_arg.input_1, substract_1_arg.input_2, *result_2);

  multiply_1_arg.input_1 = 2;
  multiply_1_arg.input_2 = 20;
  result_3 = multiply_1(&multiply_1_arg, clnt);
  if (result_3 == (int*) NULL) { clnt_perror(clnt, "call failed"); }
  printf("%i * %i = %i\n", multiply_1_arg.input_1, multiply_1_arg.input_2, *result_3);

	divide_1_arg.input_1 = 10;
  divide_1_arg.input_2 = 3;
  result_4 = divide_1(&divide_1_arg, clnt);
  if (result_4 == (float*) NULL) { clnt_perror(clnt, "call failed"); }
  printf("%i / %i = %f\n", divide_1_arg.input_1, divide_1_arg.input_2, *result_4);

#ifndef DEBUG
  clnt_destroy(clnt);
#endif /* DEBUG */
}

int main(int argc, char* argv[]) {
  char* host;

  if (argc < 2) {
    printf("usage: %s server_host\n", argv[0]);
    exit(1);
  }
  host = argv[1];
  calculator_1(host);
  exit(0);
}
