/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calculator.h"

bool_t
xdr_input (XDR *xdrs, input *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->input_1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->input_2))
		 return FALSE;
	return TRUE;
}
